name: Auto Commit and Push

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
    - cron: "0 15 * * *"     # 10:00 AM EST (3:00 PM UTC)
    - cron: "0 3 * * *"      # 10:00 PM EST (3:00 AM UTC)
  workflow_dispatch:

permissions:
  contents: write  # Allow write permissions for commit and push

jobs:
  commit-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
            node-version: '18'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Show git diff (for debugging)
        run: git diff  # This will show any changes in the repository

      - name: Run the commit script
        run: |
          # Run the autoCommit.js script
          node autoCommit.js

      - name: Force commit if there are changes
        run: |
          # Force a commit even if there are no changes detected
          git add .
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"
          git push
