name: Auto Commit and Push

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:

permissions:
  contents: write  # Ensure it has write permissions to commit and push

jobs:
  commit-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure Git
        run: |
          git config --global user.name "JBassard97"
          git config --global user.email "jonathanacciarito@gmail.com"

      - name: Run the textChange.js Script
        run: |
          node textChange.js

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"
          git remote set-url origin https://$GITHUB_TOKEN@github.com/JBassard97/autoCommit.git
          git push
